interface handler {
    use jabratech:common/types.{response-error};
    use types.{active-positions-request, active-positions-response};
    active-positions: func (request: active-positions-request) -> result<active-positions-response, response-error>;
  }