interface types {

    /**
     * Record representing a request to get trade list
     * - code: response code for validation
     * - message: description of the response
     * - data: list of trades
     */
    record active-positions-response {
      code: s16,
      message: string,
      data: list<active-position>
    }
  
    /**
     * Record representing a request to get active positions
     * - user-email: email of the user
     * - pairs: list of pairs, if the value is None, it will return all active positions on all pairs
     * - party-a: counter party as a source of the position
     * - party-b: list of counterparties, if the value is None, it will return all active positions
     */
    record active-positions-request {
      user-email: string,
      pairs: option<list<u8>>,
      party-a: u8,
      party-b: option<list<u8>>,
    }

    record active-position {
        id: u64
    }
  }
  